ITEM_DATA = {
    "axe": {
        "type": "weapon",
        "name": "Топор",
        "durability": 40,
        "damage": 6,
        "weight": 4,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "spear": {
        "type": "weapon",
        "name": "Копьё",
        "durability": 40,
        "damage": 5,
        "weight": 3,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "sword": {
        "type": "weapon",
        "name": "Меч",
        "durability": 40,
        "damage": 4,
        "weight": 2,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "bow": {
        "type": "weapon",
        "name": "Лук",
        "durability": 30,
        "damage": 4,
        "weight": 1,
        "damage_type": "physical",
        "can_melee": False,
        "can_ranged": True,
    },
    "light_tome": {
        "type": "weapon",
        "name": "Фолиант «Луч света»",
        "durability": 35,
        "damage": 4,
        "weight": 1,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
    "dark_tome": {
        "type": "weapon",
        "name": "Фолиант «Теневое удушение»",
        "durability": 35,
        "damage": 7,
        "weight": 4,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
    "fire_tome": {
        "type": "weapon",
        "name": "Фолиант «Огненный шар»",
        "durability": 35,
        "damage": 5,
        "weight": 2,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
}
