ITEM_DATA = {
    "axe": {
        "type": "weapon",
        "name": "Топор",
        "description": "Тяжёлое оружие с высоким уроном, но большим весом.",
        "durability": 40,
        "max_durability": 40,
        "damage": 6,
        "weight": 4,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "spear": {
        "type": "weapon",
        "name": "Копьё",
        "description": "Универсальное оружие с хорошим балансом между уроном и весом.",
        "durability": 40,
        "max_durability": 40,
        "damage": 5,
        "weight": 3,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "sword": {
        "type": "weapon",
        "name": "Меч",
        "description": "Лёгкое и удобное оружие для ближнего боя.",
        "durability": 40,
        "max_durability": 40,
        "damage": 4,
        "weight": 2,
        "damage_type": "physical",
        "can_melee": True,
        "can_ranged": False,
    },
    "bow": {
        "type": "weapon",
        "name": "Лук",
        "description": "Оружие дальнего боя, позволяющее атаковать противника на расстоянии.",
        "durability": 30,
        "max_durability": 30,
        "damage": 4,
        "weight": 1,
        "damage_type": "physical",
        "can_melee": False,
        "can_ranged": True,
    },
    "light_tome": {
        "type": "weapon",
        "name": "Фолиант «Луч света»",
        "description": "Магический фолиант со светлой атакующей магией.",
        "durability": 35,
        "max_durability": 35,
        "damage": 4,
        "weight": 1,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
    "dark_tome": {
        "type": "weapon",
        "name": "Фолиант «Теневое удушение»",
        "description": "Тяжёлый фолиант с мощной тёмной магией.",
        "durability": 35,
        "max_durability": 35,
        "damage": 7,
        "weight": 4,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
    "fire_tome": {
        "type": "weapon",
        "name": "Фолиант «Огненный шар»",
        "description": "Фолиант с заклинанием огненной атаки.",
        "durability": 35,
        "max_durability": 35,
        "damage": 5,
        "weight": 2,
        "damage_type": "magical",
        "can_melee": True,
        "can_ranged": True,
    },
    "healing_potion": {
        "type": "item",
        "name": "Зелье лечения",
        "description": "Восстанавливает 10 единиц здоровья.",
        "durability": 3,
        "max_durability": 3,
        "heal": 10,
    },
}
